POSITIVE_LAS_DIR = "data/POSITIVE.las"
NEGATIVE_LAS_DIR = "data/NEGATIVE.las"
COMBINED_LAS_DIR = "data/COMBINED.las"

POSITIVE_GEOTIFF_DIR = "data/POSITIVE_STANDARDISED.tif"
NEGATIVE_GEOTIFF_DIR = "data/NEGATIVE_STANDARDISED.tif"
COMBINED_GEOTIFF_DIR = "data/COMBINED_STANDARDISED.tif"

KEEP_DIMS = ["x", "y", "z", "intensity"]